### ISSUE TITLE
Set up Github Actions

### ISSUE THREAD

**Issue by amaurymartiny** [yjkimjunior/Nomidot#9]
Inspiration: https://github.com/polkadot-js/api/blob/master/.github/workflows/pr-any.yml

Only the lint job is needed for now I guess

To do after #8

**Comment by amaurymartiny** [comment]
YJ I assigned you, because I can't see the Actions tab so you might need special permissions to do that.

**Comment by amaurymartiny** [comment]
<img width="487" alt="Screenshot 2019-11-12 at 15 10 12" src="https://user-images.githubusercontent.com/1293565/68678607-8b476c80-055e-11ea-985a-1a1db85cac76.png">

Oh wait, I do see the Actions tab. Meh, you're already assigned, so I'll leave it for you :p

**Comment by yjkimjunior** [comment]
that's funny, I don't see it :/

**Comment by yjkimjunior** [comment]
<img width="590" alt="Screenshot 2019-11-12 at 15 12 56" src="https://user-images.githubusercontent.com/10432070/68678796-ed07d680-055e-11ea-8f27-e438ac04d044.png">
